### PR TITLE
"FT6202: bad FT6206_REG_VENDID!" on the current M5Stack Core2 revision

### PR DESCRIPTION
**Pull request by Fuji-P**
fix issue #1064

### CODE REVIEW

**Comment by phoddie** [comment]
Welcome, @Fuji-P! Thank you for this PR and for your help to identify this issue. We will get this merged.

We ask that contributors provide a signed [Contributor License Agreement](https://github.com/Moddable-OpenSource/moddable/tree/public/licenses#contributor-license-agreement), even for relatively small changes. Please complete the CLA when convenient.

**Comment by Fuji-P** [comment]
@phoddie 
Understood. Thank you very much. Should I fill out the form on two PDF pages and send it back? And where should I send it to?

**Comment by phoddie** [comment]
> Should I fill out the form on two PDF pages and send it back? 

Yes, please. 

> And where should I send it to?

You can email it to info@moddable.com.

Thank you.

**Comment by Fuji-P** [comment]
@phoddie 
I have sent the license agreement form to you by email.

**Comment by phoddie** [comment]
We've received the CLA. Thank you!

Closing this issue as the PR has been merged.

**Pull request closed without merging**
