### PR TITLE
Supported ATOMS3 device

### PR DESCRIPTION
**Pull request by kitazaki**
Added ATOMS3 device target files. It works fine with balls and images examples.
balls
images

Added IMU example for ATOMS3.
atoms3-imu

It also works with Node-RED dashboard in small display.
node-red-dashboard

### CODE REVIEW

**Comment by phoddie** [comment]
Great to see this port. Thank you! Very nice to have an example that uses the IMU in both gyroscope and accelerometer modes. Unfortunately, I don't have a device yet to try myself. Is there a video somewhere that shows it running?

**Comment by kitazaki** [comment]
@phoddie 
This is a simple example of Nore-RED MCU Dashboard gauge using IMU in ATOMS3.
https://twitter.com/Zakkiea/status/1609776844248846338

**Comment by phoddie** [comment]
That's fun. Thank you. Using the Dashboard UI on such a small display is a good challenge. The gauge is a good choice there.

**Comment by phoddie** [comment]
Merged!

**Pull request closed without merging**
