### PR TITLE
Add support for M5StickC

### PR DESCRIPTION
**Pull request by meganetaaan**
Hi :) This pull request adds support for [M5StickC](https://docs.m5stack.com/#/en/core/m5stickc)

running balls example on M5StickC

This contains:
* target settings
  * manifest.json that shows pin settings and ST7735 initialization sequence according to [the original library](https://github.com/m5stack/M5StickC/blob/master/src/utility/ST7735_Init.h)
  * setup-target.js that initializes button and power management ic
* Row and column offset options to ili9341 driver
* A driver for Axp192 power management IC
  * For now it has the least function necessary for putting display on
  * See example program to change screen brightness

The default baudrate and debugger speed is not available on M5StickC so you must specify them (should be documented?).

```sh
$ env ESPBAUD=1500000 DEBUGGER_SPEED=1500000 mcconfig -v -d -m -p esp32/m5stick_c
```

This is just a draft proposal. Comments are welcome.
If I need to sign to contributor license agreement things please let me know.

### CODE REVIEW

**Comment by mkellner** [comment]
Hello. We will need a CLA. They can be found in the licenses directory.

**Comment by wilberforce** [comment]
Nice! Time to order on or two of these! {EDIT] - ordered now!

**Comment by meganetaaan** [comment]
I sent you a CLA by email (to:info@moddable.com)

**Comment by mkellner** [comment]
Hello, the license statement at the top of modules/drivers/axp192/axp192.js is incomplete. Can we modify it to the following?

```
/*
 *   Copyright (c) 2019 Shinya Ishikawa
 *
 *   This file is part of the Moddable SDK Runtime.
 *
 *   The Moddable SDK Runtime is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   The Moddable SDK Runtime is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with the Moddable SDK Runtime.  If not, see <http://www.gnu.org/licenses/>.
 *
 */ 
```

**Comment by meganetaaan** [comment]
Thank you for reviewing. Sure. please modify it.

**Comment by wilberforce** [comment]
@meganetaaan My M5stick-C turned up.
I have tried the balls example as per you post above, however I'm not seeing any output in xsbug or on the screen (the backlight is off)

I'm on windows so have used:

```
set ESPBAUD=1500000
set DEBUGGER_SPEED=1500000
mcconfig -v -d -m -p esp32/m5stick_c
```

The flash looks sucessful:

```
Building xs_esp32.elf...
CC /c/Users/rhys/Projects/moddable/build/tmp/esp32/m5stick_c/debug/idf/main/main.o
AR /c/Users/rhys/Projects/moddable/build/tmp/esp32/m5stick_c/debug/idf/main/libmain.a
LD C:/Users/rhys/Projects/moddable/build/tmp/esp32/m5stick_c/debug/idf/xs_esp32.elf
esptool.py v2.6
Flashing binaries to serial port COM3 (app at offset 0x10000 )...
esptool.py v2.6
Serial port COM3
Connecting......
Chip is ESP32-PICO-D4 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, Embedded Flash, VRef calibration in efuse, Coding Scheme None
MAC: d8:a0:1d:48:3c:18
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 1500000
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 13632 bytes to 8921...
Wrote 13632 bytes (8921 compressed) at 0x00001000 in 0.1 seconds (effective 852.0 kbit/s)...
Hash of data verified.
Compressed 631232 bytes to 362919...
Wrote 631232 bytes (362919 compressed) at 0x00010000 in 5.8 seconds (effective 872.5 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 120...
Wrote 3072 bytes (120 compressed) at 0x00008000 in 0.0 seconds (effective 1536.0 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
Launching app...
```

And xsbug is getting launched with:

`/c/Users/rhys/Projects/moddable/build/bin/win/release/serial2xsbug.exe COM3 1500000 8N1 | more`

So everything looks ok.

I have another ESP32 board and I can build for this ok. Any ideas what to try next?

**Comment by wilberforce** [comment]
@meganetaaan 

Hmm. I tried flash with espruino and got a command prompt... so then tried hello world - and it worked!

So then I tried that balls demo and it worked too - so perhaps it was some sequence of the flashing commands that worked....

Thanks for doing this port!

**Comment by wilberforce** [comment]
@meganetaaan 

I do have one question - how do you stop the bouncing balls - it looks like it will run until the battery runs out and there is no way to turn off the screen?

**Comment by meganetaaan** [comment]
@wilberforce I'm happy to hear you are able to run M5StickC! I've compiled hello world first and then balls. So I think I haven't noticed any kind of sequence exists. I will investigate it when I get another M5Stack.
>I do have one question - how do you stop the bouncing balls - it looks like it will run until the battery runs out and there is no way to turn off the screen?

You can try them:

* Power on ：Long press power button for 2 seconds
* Power off ：Short press power button for 6 seconds

The document in English is here
https://docs.m5stack.com/#/en/core/m5stickc

I hope you enjoy!

**Comment by diogoviannaaraujo** [comment]
Just got my M5Stick-C, really happy.
But when trying to program it it just keeps flashing it screen and "connecting.....___" then it times out. Do I need to put it in different boot mode?
Cat find the schematics to understand how the auto gpio0 is made.

**Comment by andycarle** [comment]
@diogoviannaaraujo Double check that you're using an upload baud rate that is supported by the M5Stick-C; that's usually the issue. Try something like:
`ESPBAUD=1500000 DEBUGGER_SPEED=1500000 mcconfig -d -m -p esp32/m5stick_c`

**Comment by diogoviannaaraujo** [comment]
@andycarle No, tried that and its still just rebooting and then timeouts.

Been reading about capacitor change on cp2104 input and some people complaining about Slabs Mac driver. Will have to do more tests.

**Comment by diogoviannaaraujo** [comment]
Definitely MacOS driver bug. FTDI driver is being ignored on Catalina, I guess because of wrong signing, its using Apple's generic FTDI driver, it reboots the board but don't pull G0 pin down.

Been doing some tests with M5Camera too, I've been able to flash it but xsbug debug never starts.

**Comment by diogoviannaaraujo** [comment]
M5Stack guys released a firmware update to ftdi chip, im able to use esptool.py with it on macOS Catalina but not able to flash with moldable, maybe esptool version mismatch. It time outs wait for packet header after Configuring flash size...

**Comment by meganetaaan** [comment]
FYI with the latest Moddable SDK build ( 209f93e ), the environment variable `ESPBAUD` is now changed to `UPLOAD_SPEED` so the correct command is:

```sh
$ env UPLOAD_SPEED=1500000 DEBUGGER_SPEED=1500000 mcconfig -v -d -m -p esp32/m5stick_c
```

**Comment by diogoviannaaraujo** [comment]
Latest m5stickc usb firmware update, I can flash but cannot use xsbug, in macOS Catalina.

**Pull request closed without merging**
