### PR TITLE
syntax highlighting for code block

### PR DESCRIPTION
**Pull request by stc1988**
In my translation work, I found that some code blocks do not have syntax highlighting set.　I believe that setting syntax highlighting will make the document easier to read and will also help to notice mistakes in the code blocks.

Therefore, there might be some parts where corrections were missed, but I made corrections as much as possible.

### CODE REVIEW

**Comment by phoddie** [comment]
This is really great – thank you!

There are a couple of issues with the original JSON.

1. A few of them use `/* comments like this */` to provide instructions. Standard JSON has no comments so these are a syntax error. But, the comments are useful so maybe they should stay as-is?
2. The XS JSON parser used to permit a trailing comma (`{"foo": 1,}`) but no longer does because it is non-standard. Some of the examples use this. Should we fix these while we are making these improvements?

**Comment by stc1988** [comment]
Thank you for confirming. In the scope of this pull request, we fixed the following changes:
* remove identifiers from JSON with comments.
* remove trailing comma

**Comment by phoddie** [comment]
> remove identifiers from JSON with comments

That's a good solution. (I vaguely remember that there is a "JSON with Comments" variant in use in some ecosystems. Perhaps in the future that will be a valid identifier for GitHub markdown.)

> remove trailing comma

Perfect.

Thank you! We'll get this merged.

**Comment by mkellner** [comment]
I have merged this. It will be available in the next code-drop.

**Comment by stc1988** [comment]
> That's a good solution. (I vaguely remember that there is a "JSON with Comments" variant in use in some ecosystems. > > > Perhaps in the future that will be a valid identifier for GitHub markdown.)

I recently remembered this comment, and on GitHub, if you use the `jsonc` identifier, it will display correctly even with comments like the one below.

* jsonc
```jsonc
"include": [
	/* other includes here */
	"$(MODULES)/drivers/destm32s/manifest.json",
],
```

* json
```json
"include": [
	/* other includes here */
	"$(MODULES)/drivers/destm32s/manifest.json",
],
```

**Comment by phoddie** [comment]
Thanks for remembering this! I've updated the markdown to use "jsonc" where appropriate. That should be available shortly.

**Pull request closed without merging**
