### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by bartmichu**
Hello. Just fixing some typos, some of them in the code examples.

### CODE REVIEW

**Comment by andycarle** [comment]
@bartmichu Thank you for the corrections! 

To incorporate your changes, I will need a completed [contributor license agreement](https://github.com/Moddable-OpenSource/moddable/tree/public/licenses) from you. If you can email that to me, I'll get your fixes merged into an upcoming OSS update.

Thank you,
&nbsp;- Andy

**Comment by bartmichu** [comment]
Hey @andycarle did you get my email with CLA? I see some more typos as I read through documentation, nothing major but still I'm happy to fix them.

**Comment by andycarle** [comment]
@bartmichu Yes; thank you for the reminder! I'll get this patch merged in tomorrow and it will be applied in the next open source push. Happy to take other fixes also--thank you!

**Comment by andycarle** [comment]
I've merged this commit into our repository. You'll see it reflected here in our next open source push. 

Thank you!
&nbsp;- Andy

**Comment by andycarle** [comment]
@bartmichu This went in to the open source repository as [260e277](https://github.com/Moddable-OpenSource/moddable/commit/260e277433c581633ca9ff48d01ec5862f50dfd3). Thank you!

&nbsp;- Andy

**Pull request closed without merging**
