### PR TITLE
typing easing

### PR DESCRIPTION
**Pull request by stc1988**

### CODE REVIEW

**Comment by phoddie** [comment]
Yes, of course. Thank you.

**Comment by stc1988** [comment]
Has this been merged?

**Comment by mkellner** [comment]
@stc1988 I'm sorry, I missed it. I have merged and pushed to top-of-tree.

**Comment by stc1988** [comment]
@mkellner 
Thank you for merging.
Could you include this into SDK 4.5.0?

**Comment by mkellner** [comment]
@stc1988, for you, yes.

**Pull request closed without merging**
