### PR TITLE
Add support for M5Dial

### PR DESCRIPTION
**Pull request by stc1988**
This PR adds support for [M5Dial](https://docs.m5stack.com/en/core/M5Dial).

* 1.28" IPS 240×240 Round Display,
* Touch
* 1 button
* Rotary Encoder
* RTC

RFID is not implemented yet.

https://x.com/stc1988/status/1720805501368496516?s=20
https://x.com/stc1988/status/1720869476047184036?s=20

### CODE REVIEW

**Comment by phoddie** [comment]
Very nice! Thank you. Great videos.

Are you planning to commit the rotary dial test app too? I think that would be helpful to many developers.

**Comment by stc1988** [comment]
Sure! I'll clean my codes this weekend.

**Comment by stc1988** [comment]
I pushed example app and cleaned commit.

**Comment by phoddie** [comment]
Thank you! We'll get this merged.

**Pull request closed without merging**
