### PR TITLE
Add typings for `structuredClone` and `deepEqual`

### PR DESCRIPTION
**Pull request by meganetaaan**
Trick or treat! Here is an tiny PR to add typings for `structuredClone` and `deepEqual`. Tested to compile and work on my project [1](https://github.com/meganetaaan/stack-chan/blob/feature/outline_avatar/firmware/stackchan/face/face-renderer.ts#L212), [2](https://github.com/meganetaaan/stack-chan/blob/feature/outline_avatar/firmware/stackchan/robot.ts#L110).

### CODE REVIEW

**Comment by phoddie** [comment]
Happy Halloween!

The typings look fine and we'll get those integrated. Thank you.

FWIW – `structuredClone` has an obscure [optional second argument](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) which is also supported in the Moddable SDK. MDN documents the argument as "transferables" though appears to be more of a general options object that happens to only have a single property, `transfer`, defined.

**Comment by meganetaaan** [comment]
Thank you for your information. I have added optional `transferable` argument into the definition.
I wrote `transfer` property should accept only objects and reject primitives that will not make sense in this context. Glad if you take a look.

**Comment by phoddie** [comment]
Thank you for the update! It looks about right (though I am not so good at TypeScript...).

**Comment by phoddie** [comment]
This has been merged.

**Pull request closed without merging**
