### PR TITLE
M5 c stick brightness

### PR DESCRIPTION
**Pull request by wilberforce**
https://github.com/Moddable-OpenSource/moddable/issues/473

Update brightness so range 0-100 and works on new and old hardware

### CODE REVIEW

**Comment by phoddie** [comment]
Looks good. We'll get this integrated. Thank you!

**Comment by mkellner** [comment]
I'm not seeing good results with this change on the old m5stick_c.

Without the change: https://youtu.be/kJH7aDnzIc4
There is a range of brightnesses.

With the change: https://youtu.be/sxMPwMQNbGE
There seem to be two levels of brightness.

**Comment by wilberforce** [comment]
@mkellner 
Thanks for checking.
What ranges are you using for the values? The old was 7-15 and the new to match the Moddable Two is 0-100.

Also - are you using `setBrightness` or the `brightness=50` setter?

**Comment by wilberforce** [comment]
@mkellner 

The old `setBrightness` has been update so the range 7-15 maps to the new 0-100.

```
Button A7
WARNING: AXP192#setBrightness is deprecated. use setter, range now 0-100, now 25
Button A8
WARNING: AXP192#setBrightness is deprecated. use setter, range now 0-100, now 37
Button A9
WARNING: AXP192#setBrightness is deprecated. use setter, range now 0-100, now 50
Button A10
WARNING: AXP192#setBrightness is deprecated. use setter, range now 0-100, now 62
Button A11
WARNING: AXP192#setBrightness is deprecated. use setter, range now 0-100, now 75
```

**Comment by mkellner** [comment]
I was simply trying the example application in `examples/drivers/m5stickc-axp192`.
Would you mind updating the sample apps?

**Comment by wilberforce** [comment]
@mkellner  Done!

**Comment by mkellner** [comment]
Thank you. It'll be in the next drop.

**Pull request closed without merging**
