### PR TITLE
Feature/m5stack cores3

### PR DESCRIPTION
**Pull request by meganetaaan**
This PR is my first attempt to support for M5Stack CoreS3, the latest development board by M5Stack.

https://docs.m5stack.com/en/core/CoreS3

Available features:

- LCD(ILI9341)
- Touch screen(FT6336U)
  - Unlike the M5Stack Core2, the LCD of M5Stack CoreS3 does not have a "virtual button area" at the bottom. The touch-sensitive area is limited to a vertical range of 240 pixels. To maintain backward compatibility with Core2, an implementation has been added to consider the area from 200 to 240 pixels as virtual buttons. However, please note that this implementation may overlap with GUI elements like piu.
- Power management (Axp2101)
- Speaker

There are still many WIP:
- Dual microphone
- Camera
- Proximity sensor
- IMU
- 8MB PSRAM

### CODE REVIEW

**Comment by phoddie** [comment]
Wow. Great progress on this!!

I don't have a CoreS3 yet to try this. Despite the work-in-progress status, do you think it is usable enough that we should merge it?

I fI understand correctly, the "virtual button area" is basically for compatibility with projects that expect the A B C buttons of earlier M5Stack products. One important project that requires the buttons is Stack-chan. Is it work making the compatibility behavior optional?

- You could use `config.virtualButton` to enable it. Stack-chan can set that in the manifest. 
- If there are no virtual buttons, you could skip initializing the `button` global. That would give applications a way to check for button support at runtime.
- You might allow `config.virtualButton` to have number values indicate the height of the virtual button area, so that projects can easily customize that if desired (or you could have another configuration for that).

**Comment by meganetaaan** [comment]
Yes, I would appreciate it if we could merge this in its current state. Here are my reasons:

- I want to make the current program of Stack-chan work.
- I want to allow other CoreS3 developers to easily try it out, encouraging further contributions.

I've made the virtual buttons opt-in. If config.virtualButton is truthy, the setup script will initialize the virtual buttons. I'm not sure how much demand there will be for fine-tuning the size and position of the buttons, so I'll add those options if there's demand from other developers. For now, I thought it best to keep the implementation simple with reasonable default values.

**Comment by phoddie** [comment]
> I've made the virtual buttons opt-in. If config.virtualButton is truthy, the setup script will initialize the virtual buttons. I'm not sure how much demand there will be for fine-tuning the size and position of the buttons, so I'll add those options if there's demand from other developers. For now, I thought it best to keep the implementation simple with reasonable default values

@meganetaaan – Thank you for the quick change. That's all very reasonable.

> Yes, I would appreciate it if we could merge this in its current state. Here are my reasons:

Makes sense. We'll get that merged. Note that we may be a little slow right now because of summer holidays, but we'll do our best.

**Comment by phoddie** [comment]
Merged. Good luck!

**Comment by kairos0ne** [comment]
@meganetaaan @phoddie Any chance we could get a minor update to the docs/ here for us who want to try/test and help but no clue how.

**Comment by phoddie** [comment]
Ah, it looks like @meganetaaan didn't update the esp32.md doc yet, probably because this is still in progress. The main thing to know is that the platform target for is `esp32/m5stack_cores3`. I don't have the device, but was able to build the helloworld example as follows:

```
cd $MODDABLE/examples/helloworld
mcconfig -d -m -p esp32/m5stack_cores3
```

From the commits, it looks like display, audio, touch, networking, BLE, etc should all be working from there so the built-in examples should apply. If you have specific questions, please ask.

**Comment by kairos0ne** [comment]
OK thanks I managed to flash the hello world example and the Qrcode example...  I think this is working well... 

However I seem to have bricked my device inadvertently, 

I accidentally let go of the power button while putting onto programmable mode and switching it off shortly after... 

I get this now when trying to flash anything to it 

```
Traceback (most recent call last):
  File "/Users/admin/esp32/esp-idf/components/esptool_py/esptool/esptool.py", line 5482, in <module>
    _main()
  File "/Users/admin/esp32/esp-idf/components/esptool_py/esptool/esptool.py", line 5475, in _main
    main()
  File "/Users/admin/esp32/esp-idf/components/esptool_py/esptool/esptool.py", line 4782, in main
    esp = esp or get_default_connected_device(ser_list, port=args.port, connect_attempts=args.connect_attempts,
  File "/Users/admin/esp32/esp-idf/components/esptool_py/esptool/esptool.py", line 116, in get_default_connected_device
    _esp.connect(before, connect_attempts)
  File "/Users/admin/esp32/esp-idf/components/esptool_py/esptool/esptool.py", line 689, in connect
    last_error = self._connect_attempt(mode=mode, usb_jtag_serial=usb_jtag_serial, extra_delay=extra_delay)
  File "/Users/admin/esp32/esp-idf/components/esptool_py/esptool/esptool.py", line 639, in _connect_attempt
    self.bootloader_reset(usb_jtag_serial, extra_delay)
  File "/Users/admin/esp32/esp-idf/components/esptool_py/esptool/esptool.py", line 623, in bootloader_reset
    self._setDTR(False)  # IO0=HIGH, done
  File "/Users/admin/esp32/esp-idf/components/esptool_py/esptool/esptool.py", line 557, in _setDTR
    self._port.setDTR(state)
  File "/Users/admin/.espressif/python_env/idf4.4_py3.9_env/lib/python3.9/site-packages/serial/serialutil.py", line 603, in setDTR
    self.dtr = value
  File "/Users/admin/.espressif/python_env/idf4.4_py3.9_env/lib/python3.9/site-packages/serial/serialutil.py", line 473, in dtr
    self._update_dtr_state()
  File "/Users/admin/.espressif/python_env/idf4.4_py3.9_env/lib/python3.9/site-packages/serial/serialposix.py", line 715, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIC, TIOCM_DTR_str)
OSError: [Errno 6] Device not configured
CMake Error at run_serial_tool.cmake:56 (message):
  /Users/admin/.espressif/python_env/idf4.4_py3.9_env/bin/python
  /Users/admin/esp32/esp-idf/components/esptool_py/esptool/esptool.py --chip
  esp32s3 failed
```

Any advice on how I can format it start again would be a real life saver at this point.

**Comment by kairos0ne** [comment]
Ok scratch that post (deleted)... 

I've reformatted the core3 and flashed many of the examples to it with success.

**Comment by kairos0ne** [comment]
If there anything else in particular you need tested for this?

**Comment by phoddie** [comment]
> I've reformatted the core3 and flashed many of the examples to it with success

Excellent news!

> If there anything else in particular you need tested for this?

@meganetaaan may have some ideas. Here are two areas that I thought of:
1. As noted above, there is special touch support to emulate buttons M5Stack physical buttons. Did you happen to try any examples that use touch? A good example for that is [piu/drag](https://github.com/Moddable-OpenSource/moddable/blob/public/examples/piu/drag/main.js). If you are feeling ambitious, you might modify it to eliminate the border so you can test touch all the way to the bottom edge (which is where the M5Stack compatibility area is).
2. There's also some complexity around audio. Did you try the [piu/sound](https://github.com/Moddable-OpenSource/moddable/blob/public/examples/piu/sound/main.js) example?

**Comment by kairos0ne** [comment]
>As noted above, there is special touch support to emulate buttons M5Stack physical buttons. Did you happen to try any examples that use touch? A good example for that is [piu/drag](https://github.com/Moddable-OpenSource/moddable/blob/public/examples/piu/drag/main.js). If you are feeling ambitious, you might modify it to eliminate the border so you can test touch all the way to the bottom edge (which is where the M5Stack compatibility area is).

I can report the example works well, I'll try the the border as recommended this evening. Although the drag drops if you move too quickly but I think thats down to the implementation of the example. 

 >There's also some complexity around audio. Did you try the [piu/sound](https://github.com/Moddable-OpenSource/moddable/blob/public/examples/piu/sound/main.js) example?
 
 I can report the sound example works well. 

I would love to see the mics implemented as this is core to the app I'm building... I read the notes above and if @meganetaaan you require any testing to help that process, let me know.

**Comment by phoddie** [comment]
@kairos0ne – thanks for the good news. And so quickly.

> Although the drag drops if you move too quickly but I think thats down to the implementation of the example.

I wasn't able to reproduce this on a Moddable Two. In looking at the code, I would expect the drag to continue tracking until the driver reports there is no touch detected -- only `onTouchEnded` stops the tracking. Is it possible your finger sometimes crosses past the edge of the display / touch sensor? That would do it.

> I would love to see the mics implemented as this is core to the app I'm building...

Me too! I have a project I'm trying to finish up that uses audio input. @meganetaaan – the Moddable team should have our M5Stack Core3 next week, so please let us know if we can assist in some way.

**Comment by kairos0ne** [comment]
@phoddie I double checked and back tested the core2 and they have similar behavior, it's not great for the drag and drop if you move fast it doesn't register the drag. I will look at the it and see if I can see what's causing it.

**Comment by kairos0ne** [comment]
I suspect the finger moves out off the hit area for the button before the onTouchMove function is called and the button looses focus. Not sure will look.

**Comment by kairos0ne** [comment]
I changed the touch count to 1 and things improved somewhat. Also removed the border as suggested: https://amnesia.io/937143469e0102395265d7b56b1123a88881dfb2c1502d84beb00e9dc5a2e884

**Comment by phoddie** [comment]
> I changed the touch count to 1 and things improved somewhat.

@kairos0ne - Perhaps that's a hint. I wonder if sometimes when you are moving very quickly it is triggering a multitouch case? If that happens, the `id` argument to `onTouchBegan`, `onTouchMoved`, and/or `onTouchEnded` would be non-zero. The `id` should normally be zero for single touch cases. Could you add some tracing / debugging code to see if the `id` ever has a non-zero value?

**Comment by kairos0ne** [comment]
I'll have a dig with some debug code and see whats what... I'd like to have proper look at xsbug anyway and I have some time now, besides I need scroll for my menus for the game I'm building so would make sense for me to learn more in this area.

**Pull request closed without merging**
