### PR TITLE
qrcode piu example

### PR DESCRIPTION
**Pull request by wilberforce**

### CODE REVIEW

**Comment by phoddie** [comment]
Thank you, but already committed my example to the Moddable SDK repository earlier this afternoon. ;)

**Comment by wilberforce** [comment]
oh poos.

**Comment by phoddie** [comment]
Sorry about that. At least we both had the same great idea.

**Comment by wilberforce** [comment]
> Sorry about that. At least we both had the same great idea.

I had done a git pull before my branch as well ;-)

**Pull request closed without merging**
