### PR TITLE
esp32 mcrun $(DEBUGGER_SPEED)

### PR DESCRIPTION
**Pull request by wilberforce**

### CODE REVIEW

**Comment by phoddie** [comment]
Oh, cool. Thanks.

That just missed our merge today. We'll get it for the next one. We'll need to add the parallel change for macOS and Linux.

**Comment by wilberforce** [comment]
> Oh, cool. Thanks.
> 
> That just missed our merge today. We'll get it for the next one. We'll need to add the parallel change for macOS and Linux.

The only reference was to the ESP32 mcrun nmake file - So wont effect macOS and linux.  Possibly there could be esp8266 updates needed?

**Comment by wilberforce** [comment]
@phoddie 

Here are the other references that need updating to `$(DEBUGGER_SPEED)` 

( needs the init also needs be added too ):

`UPLOAD_PORT ?= 921600 `

`UPLOAD_PORT ?= 460800`

https://github.com/Moddable-OpenSource/moddable/blob/40162325723fa17b1b64158aee645e46ef16ab2d/tools/mcrun/nmake.esp.mk#L57

https://github.com/Moddable-OpenSource/moddable/blob/5086059145b6d2b067c68a0322f93c40be00e299/tools/mcrun/make.esp.mk#L78

https://github.com/Moddable-OpenSource/moddable/blob/public/tools/mcrun/make.esp32.mk#L74

https://github.com/Moddable-OpenSource/moddable/blob/public/tools/mcrun/make.esp32.mk#L78

**Comment by phoddie** [comment]
Closing, as this has been merged.

**Pull request closed without merging**
