### PR TITLE
[WIP] Adding I2C timeout

### PR DESCRIPTION
**Pull request by k45514n**
I'm a little stuck here, but this is as far as I've gotten.

### CODE REVIEW

**Comment by andycarle** [comment]
Hi Kas,

This is definitely headed in the right direction. Including this configuration option in the constructor's options object seems correct to me.

The rest of the work to be done is basically chasing the change through the I2C implementations on each of the platforms. If it's okay with you, I can take what you've started here and then drop in the platform-specific bits.

To do that, we'll need a completed [CLA](https://github.com/Moddable-OpenSource/moddable/blob/78caaabe6ead2eac7ba82a20a8e755ba948f1e6d/licenses/Moddable%20CLA%20-%20individual.pdf) from you — you could post that here or email it to us.

Cheers!
&nbsp;- Andy

**Comment by k45514n** [comment]
Where do I email it to? It has my mailing address so I'd rather not post it here heh.

**Comment by andycarle** [comment]
info@moddable.com would be just fine. Thanks!

**Comment by k45514n** [comment]
So sorry for delays (getting married, etc.) sending now.

**Comment by k45514n** [comment]
I sent the form in October, is there anything else blocking this? If you give me a lead of where to start in the C I can move this forward if you like.

**Comment by andycarle** [comment]
@nodebotanist Thank you for the reminder--let me take a look at this over the weekend and see if we can wrap it up.

**Comment by andycarle** [comment]
@nodebotanist I've incorporated the above commit into our tree and built on it to implement i2c timeout configuration on ESP8266 and ESP32. You'll see that update + a basic driver and example app for the Qwiic Twist in our next open source push.

**Comment by andycarle** [comment]
@nodebotanist These changes are now live in the open source repo. The new Qwiic Twist driver is [here](https://github.com/Moddable-OpenSource/moddable/tree/public/modules/drivers/qwiictwist) and the example is [here](https://github.com/Moddable-OpenSource/moddable/tree/public/examples/drivers/qwiictwist). Cheers!

**Pull request closed without merging**
