### PR TITLE
Examples: clean up

### PR DESCRIPTION
**Pull request by bartmichu**

### CODE REVIEW

**Comment by phoddie** [comment]
@bartmichu - I don't have an objection to changing http to https in the Creative Commons link. However, we have tried to follow the guidance from the license creators where practical. Creative Commons, as of this writing, still [recommends an http link](https://creativecommons.org/choose/non-web-popup?license_code=by&amp;jurisdiction=&amp;version=4.0&amp;lang=en).

I'm curious if you are aware of precedent for making this kind of change in other projects. Thanks.

**Comment by bartmichu** [comment]
@phoddie Sorry for delay, somehow I've missed your comment. No, I'm not aware of any. I guess I'm in "https everywhere" camp, but if that's what they recommend then maybe it is better to leave it for now.

Should I create a new pull request without CC link change? This one fixes some typos in separate commit.

**Comment by phoddie** [comment]
@bartmichu -- I just checked the Creative Commons [site](https://creativecommons.org/choose/non-web-popup?license_code=by&amp;jurisdiction=&amp;version=4.0&amp;lang=en) Their recommended text still uses `http`, not `https`. I understand your point and the intent is good, but I hesitate to make any changes to a license. So, if you don't mind updating the PR without the CC link change, that would perfect. Thank you!

**Comment by bartmichu** [comment]
I believe it's all resolved now in the latest release so I will close this PR.

**Pull request closed without merging**
