### PR TITLE
Feature/typings io

### PR DESCRIPTION
**Pull request by meganetaaan**
This PR adds typings for `embedded/io` modules, which include:

- Digital/DigitalBank
- Analog(Input)
- I2C
- PWM
- PulseCount
- Serial
- SPI
- Socket (TCP/UDP) and listener

The discussion is https://github.com/Moddable-OpenSource/moddable/discussions/926

### CODE REVIEW

**Comment by meganetaaan** [comment]
I've tested to compile `io` examples. I think It is ready to review.

Several notes:

- When I added a type definition to `examples/manifest_typings.json`, I got an error of `mcmanifest`. So I took a workaround changing prefix from `:` to `_` for the directory name.

```json
		"embedded:io/socket/*": [
			"$(TYPINGS)/embedded:io/socket/*"
		]
```

```
/home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/echo/makefile:886: *** ターゲットパターンが '%' を含んでいません.  中止.
```

- I see `io` network examples have many convenient helper classes like `fetch`, `HTTPClient`, and `WebSocket`. I think they are also worth being typed in the future.
- I got an error compiling `udp.c`

<details>
<summary>full log</summary>

```
sskw@sskw-XF:/work/ghq/github.com/meganetaaan/moddable/examples/io/listener/simplehttpserver$ mcconfig -d -m -p esp32/m5stack -t build
/home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/simplehttpserver/makefile:887: 警告: ターゲット '/home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/simplehttpserver/modules/~.embedded/io/socket/udp.xsb' のためのレシピを置き換えます
/home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/simplehttpserver/makefile:862: 警告: ターゲット '/home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/simplehttpserver/modules/~.embedded/io/socket/udp.xsb' のための古いレシピは無視されます
# Reconfiguring ESP-IDF...
Executing action: reconfigure
Running cmake in directory /home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/simplehttpserver/xsProj-esp32/build
Executing "cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -DSDKCONFIG_DEFAULTS=/home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/simplehttpserver/xsProj-esp32/sdkconfig.mc -DSDKCONFIG_HEADER=/home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/simplehttpserver/xsProj-esp32/build/config/sdkconfig.h -DCMAKE_MESSAGE_LOG_LEVEL=ERROR -DDEBUGGER_SPEED=460800 -DIDF_TARGET=esp32 -DESP32_SUBCLASS=esp32 -DCCACHE_ENABLE=0 /home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/simplehttpserver/xsProj-esp32"...
-- Building ESP-IDF components for target esp32
-- Project sdkconfig file /home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/simplehttpserver/xsProj-esp32/sdkconfig
Loading defaults file /home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/simplehttpserver/xsProj-esp32/sdkconfig.mc...
-- App "xs_esp32" version: OS220805b-16-g45bea029
-- Adding linker script /home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/simplehttpserver/xsProj-esp32/build/esp-idf/esp_system/ld/memory.ld
-- Adding linker script /home/sskw/.local/share/esp32/esp-idf/components/esp_system/ld/esp32/sections.ld.in
-- Adding linker script /home/sskw/.local/share/esp32/esp-idf/components/esp_rom/esp32/ld/esp32.rom.ld
-- Adding linker script /home/sskw/.local/share/esp32/esp-idf/components/esp_rom/esp32/ld/esp32.rom.api.ld
-- Adding linker script /home/sskw/.local/share/esp32/esp-idf/components/esp_rom/esp32/ld/esp32.rom.libgcc.ld
-- Adding linker script /home/sskw/.local/share/esp32/esp-idf/components/esp_rom/esp32/ld/esp32.rom.newlib-data.ld
-- Adding linker script /home/sskw/.local/share/esp32/esp-idf/components/esp_rom/esp32/ld/esp32.rom.syscalls.ld
-- Adding linker script /home/sskw/.local/share/esp32/esp-idf/components/esp_rom/esp32/ld/esp32.rom.newlib-funcs.ld
-- Adding linker script /home/sskw/.local/share/esp32/esp-idf/components/esp_rom/esp32/ld/esp32.rom.newlib-time.ld
-- Adding linker script /home/sskw/.local/share/esp32/esp-idf/components/soc/esp32/ld/esp32.peripherals.ld
-- Components: app_trace app_update asio bootloader bootloader_support bt cbor cmock coap console cxx driver efuse esp-tls esp32 esp_adc_cal esp_common esp_eth esp_event esp_gdbstub esp_hid esp_http_client esp_http_server esp_https_ota esp_https_server esp_hw_support esp_ipc esp_lcd esp_local_ctrl esp_netif esp_phy esp_pm esp_ringbuf esp_rom esp_serial_slave_link esp_system esp_timer esp_websocket_client esp_wifi espcoredump esptool_py expat fatfs freemodbus freertos hal heap idf_test ieee802154 jsmn json libsodium log lwip main mbedtls mdns mqtt newlib nghttp nvs_flash openssl openthread partition_table perfmon protobuf-c protocomm pthread sdmmc soc spi_flash spiffs tcp_transport tcpip_adapter tinyusb ulp unity usb vfs wear_levelling wifi_provisioning wpa_supplicant xtensa
-- Component paths: /home/sskw/.local/share/esp32/esp-idf/components/app_trace /home/sskw/.local/share/esp32/esp-idf/components/app_update /home/sskw/.local/share/esp32/esp-idf/components/asio /home/sskw/.local/share/esp32/esp-idf/components/bootloader /home/sskw/.local/share/esp32/esp-idf/components/bootloader_support /home/sskw/.local/share/esp32/esp-idf/components/bt /home/sskw/.local/share/esp32/esp-idf/components/cbor /home/sskw/.local/share/esp32/esp-idf/components/cmock /home/sskw/.local/share/esp32/esp-idf/components/coap /home/sskw/.local/share/esp32/esp-idf/components/console /home/sskw/.local/share/esp32/esp-idf/components/cxx /home/sskw/.local/share/esp32/esp-idf/components/driver /home/sskw/.local/share/esp32/esp-idf/components/efuse /home/sskw/.local/share/esp32/esp-idf/components/esp-tls /home/sskw/.local/share/esp32/esp-idf/components/esp32 /home/sskw/.local/share/esp32/esp-idf/components/esp_adc_cal /home/sskw/.local/share/esp32/esp-idf/components/esp_common /home/sskw/.local/share/esp32/esp-idf/components/esp_eth /home/sskw/.local/share/esp32/esp-idf/components/esp_event /home/sskw/.local/share/esp32/esp-idf/components/esp_gdbstub /home/sskw/.local/share/esp32/esp-idf/components/esp_hid /home/sskw/.local/share/esp32/esp-idf/components/esp_http_client /home/sskw/.local/share/esp32/esp-idf/components/esp_http_server /home/sskw/.local/share/esp32/esp-idf/components/esp_https_ota /home/sskw/.local/share/esp32/esp-idf/components/esp_https_server /home/sskw/.local/share/esp32/esp-idf/components/esp_hw_support /home/sskw/.local/share/esp32/esp-idf/components/esp_ipc /home/sskw/.local/share/esp32/esp-idf/components/esp_lcd /home/sskw/.local/share/esp32/esp-idf/components/esp_local_ctrl /home/sskw/.local/share/esp32/esp-idf/components/esp_netif /home/sskw/.local/share/esp32/esp-idf/components/esp_phy /home/sskw/.local/share/esp32/esp-idf/components/esp_pm /home/sskw/.local/share/esp32/esp-idf/components/esp_ringbuf /home/sskw/.local/share/esp32/esp-idf/components/esp_rom /home/sskw/.local/share/esp32/esp-idf/components/esp_serial_slave_link /home/sskw/.local/share/esp32/esp-idf/components/esp_system /home/sskw/.local/share/esp32/esp-idf/components/esp_timer /home/sskw/.local/share/esp32/esp-idf/components/esp_websocket_client /home/sskw/.local/share/esp32/esp-idf/components/esp_wifi /home/sskw/.local/share/esp32/esp-idf/components/espcoredump /home/sskw/.local/share/esp32/esp-idf/components/esptool_py /home/sskw/.local/share/esp32/esp-idf/components/expat /home/sskw/.local/share/esp32/esp-idf/components/fatfs /home/sskw/.local/share/esp32/esp-idf/components/freemodbus /home/sskw/.local/share/esp32/esp-idf/components/freertos /home/sskw/.local/share/esp32/esp-idf/components/hal /home/sskw/.local/share/esp32/esp-idf/components/heap /home/sskw/.local/share/esp32/esp-idf/components/idf_test /home/sskw/.local/share/esp32/esp-idf/components/ieee802154 /home/sskw/.local/share/esp32/esp-idf/components/jsmn /home/sskw/.local/share/esp32/esp-idf/components/json /home/sskw/.local/share/esp32/esp-idf/components/libsodium /home/sskw/.local/share/esp32/esp-idf/components/log /home/sskw/.local/share/esp32/esp-idf/components/lwip /home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/simplehttpserver/xsProj-esp32/main /home/sskw/.local/share/esp32/esp-idf/components/mbedtls /home/sskw/.local/share/esp32/esp-idf/components/mdns /home/sskw/.local/share/esp32/esp-idf/components/mqtt /home/sskw/.local/share/esp32/esp-idf/components/newlib /home/sskw/.local/share/esp32/esp-idf/components/nghttp /home/sskw/.local/share/esp32/esp-idf/components/nvs_flash /home/sskw/.local/share/esp32/esp-idf/components/openssl /home/sskw/.local/share/esp32/esp-idf/components/openthread /home/sskw/.local/share/esp32/esp-idf/components/partition_table /home/sskw/.local/share/esp32/esp-idf/components/perfmon /home/sskw/.local/share/esp32/esp-idf/components/protobuf-c /home/sskw/.local/share/esp32/esp-idf/components/protocomm /home/sskw/.local/share/esp32/esp-idf/components/pthread /home/sskw/.local/share/esp32/esp-idf/components/sdmmc /home/sskw/.local/share/esp32/esp-idf/components/soc /home/sskw/.local/share/esp32/esp-idf/components/spi_flash /home/sskw/.local/share/esp32/esp-idf/components/spiffs /home/sskw/.local/share/esp32/esp-idf/components/tcp_transport /home/sskw/.local/share/esp32/esp-idf/components/tcpip_adapter /home/sskw/.local/share/esp32/esp-idf/components/tinyusb /home/sskw/.local/share/esp32/esp-idf/components/ulp /home/sskw/.local/share/esp32/esp-idf/components/unity /home/sskw/.local/share/esp32/esp-idf/components/usb /home/sskw/.local/share/esp32/esp-idf/components/vfs /home/sskw/.local/share/esp32/esp-idf/components/wear_levelling /home/sskw/.local/share/esp32/esp-idf/components/wifi_provisioning /home/sskw/.local/share/esp32/esp-idf/components/wpa_supplicant /home/sskw/.local/share/esp32/esp-idf/components/xtensa
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/simplehttpserver/xsProj-esp32/build
# tsc tsconfig.json
# xsc ~.embedded/io/socket/udp.xsb
# xsc mc/config.xsb
# xsc main.xsb
# xsc commodetto/PixelsOut.xsb
# xsid udp.c.xsi
# xsl modules
### 529 instances, 760 keys, 64 colors, 0 holes
# cc mc.xs.c (slots in flash)
# mcrez resources
Total resource size: 21078 bytes
# cc mc.resources.c (slots in flash)
# cc udp.c.o
/home/sskw/.local/share/moddable/modules/io/socket/lwip/udp.c:64:2: error: 'xs_udp_destructor' undeclared here (not in a function); did you mean 'xs_tcp_destructor'?
  xs_udp_destructor,
  ^~~~~~~~~~~~~~~~~
  xs_tcp_destructor
make: *** [/home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/simplehttpserver/makefile:1109: /home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/simplehttpserver/udp.c.o] エラー 1
```
</details>

```
/home/sskw/.local/share/moddable/modules/io/socket/lwip/udp.c:64:2: error: 'xs_udp_destructor' undeclared here (not in a function); did you mean 'xs_tcp_destructor'?
  xs_udp_destructor,
  ^~~~~~~~~~~~~~~~~
  xs_tcp_destructor
```

Kind of "function referred before the declaration" error. So adding `void xs_udp_destructor(void *data);` to the top of `udp.c` resolved the error. But I couldn't find the root cause. I think something is bad about my compiler environment.

**Comment by phoddie** [comment]
> I got an error compiling udp.c

Me too.  The solution is to rename `udp.ts` to `udp.d.ts`.

> So I took a workaround changing prefix from : to _ for the directory name.

I don't think macOS likes colon `:` characters in file names. That was the original path separator in HFS. Your workaround is reasonable.

> I see io network examples have many convenient helper classes like fetch, HTTPClient, and WebSocket. I think they are also worth being typed in the future

`fetch`, `WebSocket` and `mqtt` are all well known APIs. There should already be TypeScript declarations for them somewhere to use as a starting point. `HTTPClient`, `MQTTClient`, and `WebSocketClient` are all part of ECMA-419 2nd edition, so someone (you??!?) will need to create typings for them. All of these will migrate from examples to modules in time. Some more information is [here](https://github.com/Moddable-OpenSource/moddable/blob/public/examples/io/tcp/readme.md#moddable-sdk---tcp-io-examples).

I had some problems running $MODDABLE/examples/io/digital/blink. To run with TypeScript, I changed main.js to main.ts and adding manifest_typings.json to the manifest. That gives some errors. I know `System` isn't official but `device` should work?

```
main.ts:15:17 - error TS2304: Cannot find name 'device'.

15 const Digital = device.io.Digital;
                   ~~~~~~
main.ts:17:9 - error TS2304: Cannot find name 'device'.

17    pin: device.pin.led,
           ~~~~~~
main.ts:23:1 - error TS2304: Cannot find name 'System'.
23 System.setInterval(() => {
   ~~~~~~
```

**Comment by meganetaaan** [comment]
>Me too. The solution is to rename udp.ts to udp.d.ts.

Uh oh. Fixed!

>I had some problems running $MODDABLE/examples/io/digital/blink. To run with TypeScript, I changed main.js to main.ts and adding manifest_typings.json to the manifest. That gives some errors. I know System isn't official but device should work?

I hadn't prepared to enable the `device` variable for the global context. Now I did by these commits above. We can compile examples by renaming(js->ts) and adding manifest_typings.

I put [one common `device` type definition](https://github.com/Moddable-OpenSource/moddable/blob/7d31a9c0574b710a4c737311285c49aba3407c08/typings/embedded_provider/builtin.d.ts). But it could be better for each device to have its own `device` definition under `target/[devicename]` directory. I will think about it for the next step after merging this PR.

**Comment by phoddie** [comment]
This has been merged. I applied a few changes after merging. I think they are straightforward, but let me know if you have questions about them. I haven't completed my review yet.

Thank you again for getting this effort started. It is going to be helpful to many developers to have TypeScript support for the ECMA-419 APIs.

**Pull request closed without merging**
